# This is a basic workflow to help you get started with Actions

name: check-auto-patch

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
  - cron: "0 10 * * 1"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      amount : ${{ steps.commit-amount.outputs.amount }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: DaanV2/action-commit-amount-last-release@latest
        id: commit-amount
      
  patch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [check]
    if: ${{ needs.check.outputs.amount > 10 }}

    steps:
      - name: ğŸ“¦ Checkout Repository
        uses: actions/checkout@v5

      - name: setup git
        run: |
          git config --global user.email "orbi@blockception.com"
          git config --global user.name "Orbi-bot"

      - name: ğŸ—ï¸ Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version-file: .nvmrc

      - name: Build
        run: npm ci

      - name: Patch
        run: npm version patch
